### ISSUE TITLE
Unable to assign device on testnet

### ISSUE THREAD

**Issue by PodTheCoder** [edge/wallet#259]
Error assigning device on https://wallet.test.network/staking. Error message after clicking Assign Stake:
"Cannot destructure property 'metadata' of '(intermediate value)' as it is null."

<img width="917" alt="edge_assign_device_bug_testnet - Copy" src="https://github.com/edge/wallet/assets/113918164/0cd486db-7301-416e-a7fc-9dbcc4e7ecaa">

Notably, the device address displays correctly but the url is wrong: https://wallet.test.network/undefined/node/xe_1A662B90eFb6Ee0Cf8836d972B36FA604fc04627

Reproduction:

- Go to https://wallet.test.network/staking
- Click Assign Device next to a stake.
- Enter device code or fill in the fields manually. Both methods give the same error.
- Click `Assign Stake`

Testnet example device code:
eyJhZGRyZXNzIjoieGVfMUE2NjJCOTBlRmI2RWUwQ2Y4ODM2ZDk3MkIzNkZBNjA0ZmMwNDYyNyIsInByaXZhdGVLZXkiOiIyNmE2YmQ1OTIwNDM4NThjMjlkMjMwODM0YWFiNWZmZWQ0MjQ5ZWNlMDVkODYzNzhlNTQ0Zjk0ODgyOTk2MTdmIn0

Decoded:
{"address":"xe_1A662B90eFb6Ee0Cf8836d972B36FA604fc04627","privateKey":"26a6bd592043858c29d230834aab5ffed4249ece05d86378e544f9488299617f"}

**Comment by annybs** [comment]
These bugs emerged in testnet over the weekend as a byproduct of merging #253 - whereby the majority of components were updated correctly over a number of rebases, but the device assignment modal was not, as it was new.

This is now fixed in ff9f7d7 and should not be an issue in mainnet once deployed there.
